[package]
name = "rust_os"
version = "0.1.0"
authors = ["Luna1996 <wyf19960926@gmail.com>"]
edition = "2018"

[workspace]
members = ["uefi","elf"]

[dev-dependencies]
uefi = {path = "uefi"}
elf = {path = "elf"}